### ISSUE TITLE
升级了Monterey，但问题较多，不知道大佬是否有计划适配Monterey

### ISSUE THREAD

**Issue by ssr20001** [lxyoucan/Lenovo-LEGION-i7-4720HQ-hd4600-14-OpenCore-Hackintosh#4]
稍微改了下强上了Monterey
未解决：
1、现在蓝牙换用 BlueToolFixup 还是无法驱动（BCM94352Z）
2、不定时关机（启动10分钟左右必定自动关机，除非删除FakePCIID，但此时开关机又会异常的慢，好像还导致USB不正常？）
已解决：
1、读不到启动盘之外的第二块硬盘，添加 ExFatDxe 后解决
2、关机变重启，添加 CpuTscSync 后解决
![psc](https://user-images.githubusercontent.com/70944645/139169976-7245dd59-9ddf-4889-87d5-2e4c33229c8c.jpg)

**Comment by lxyoucan** [comment]
抱歉，最近有些忙，暂时没升级Monterey的打算
